package db

import (
	"database/sql"
	"time"
)

// Application holds all the information about an application
type Application struct {
	RowID                                  string
	ID                                     sql.NullInt32
	MemberID                               sql.NullString
	FirstName                              sql.NullString
	LastName                               sql.NullString
	Address                                sql.NullString
	DOB                                    sql.NullString
	Phone                                  sql.NullString
	LoanAmnt                               sql.NullInt32
	FundedAmnt                             sql.NullInt32
	FundedAmntInv                          sql.NullInt32
	Term                                   sql.NullString
	IntRate                                sql.NullString
	Installment                            sql.NullInt32
	Grade                                  sql.NullString
	SubGrade                               sql.NullString
	HomeOwnership                          sql.NullString
	AnnualInc                              sql.NullInt32
	VerificationStatus                     sql.NullString
	IssueD                                 sql.NullString
	PymntPlan                              sql.NullString
	URL                                    sql.NullString
	Desc                                   sql.NullString
	Purpose                                sql.NullString
	Title                                  sql.NullString
	ZipCode                                sql.NullString
	AddrState                              sql.NullString
	DTI                                    sql.NullInt32
	Delinq2Yrs                             sql.NullInt32
	EarliestCrLine                         sql.NullString
	InqLast6Mths                           sql.NullInt32
	MthsSinceLastDelinq                    sql.NullInt32
	MthsSinceLastRecord                    sql.NullInt32
	OpenAcc                                sql.NullInt32
	PubRec                                 sql.NullInt32
	RevolBal                               sql.NullInt32
	RevolUtil                              sql.NullString
	TotalAcc                               sql.NullInt32
	InitialListStatus                      sql.NullString
	OutPrncp                               sql.NullInt32
	OutPrncpInv                            sql.NullInt32
	TotalPymnt                             sql.NullInt32
	TotalPymntInv                          sql.NullInt32
	TotalRecPrncp                          sql.NullInt32
	TotalRecInt                            sql.NullInt32
	TotalRecLateFee                        sql.NullInt32
	Recoveries                             sql.NullInt32
	CollectionRecoveryFee                  sql.NullInt32
	LastPymntD                             sql.NullString
	LastPymntAmnt                          sql.NullInt32
	NextPymntD                             sql.NullString
	LastCreditPullD                        sql.NullString
	Collections12MthsExMed                 sql.NullInt32
	MthsSinceLastMajorDerog                sql.NullInt32
	PolicyCode                             sql.NullInt32
	ApplicationType                        sql.NullString
	AnnualIncJoint                         sql.NullInt32
	DtiJoint                               sql.NullString
	VerificationStatusJoint                sql.NullInt32
	AccNowDelinq                           sql.NullInt32
	TotCollAmt                             sql.NullInt32
	TotCurBal                              sql.NullInt32
	OpenAcc6m                              sql.NullString
	OpenActIl                              sql.NullString
	OpenIl12m                              sql.NullString
	OpenIl24m                              sql.NullString
	MthsSinceRcntIl                        sql.NullInt32
	TotalBalIl                             sql.NullInt32
	IlUtil                                 sql.NullInt32
	OpenRv12m                              sql.NullString
	OpenRv24m                              sql.NullString
	MaxBalBc                               sql.NullInt32
	AllUtil                                sql.NullString
	TotalRevHiLim                          sql.NullString
	InqFi                                  sql.NullString
	TotalCuTl                              sql.NullString
	InqLast12m                             sql.NullString
	AccOpenPast24mths                      sql.NullString
	AvgCurBal                              sql.NullString
	BcOpenToBuy                            sql.NullString
	BcUtil                                 sql.NullString
	ChargeoffWithin12Mths                  sql.NullInt32
	DelinqAmnt                             sql.NullInt32
	MoSinOldIlAcct                         sql.NullInt32
	MoSinOldRevTlOp                        sql.NullInt32
	MoSinRcntRevTlOp                       sql.NullInt32
	MoSinRcntTl                            sql.NullString
	MortAcc                                sql.NullString
	MthsSinceRecentBc                      sql.NullInt32
	MthsSinceRecentBcDlq                   sql.NullInt32
	MthsSinceRecentInq                     sql.NullInt32
	MthsSinceRecentRevolDelinq             sql.NullInt32
	NumAcctsEver120Pd                      sql.NullInt32
	NumActvBcTl                            sql.NullInt32
	NumActvRevTl                           sql.NullInt32
	NumBcSats                              sql.NullInt32
	NumBcTl                                sql.NullInt32
	NumIlTl                                sql.NullInt32
	NumOpRevTl                             sql.NullInt32
	NumRevAccts                            sql.NullInt32
	NumRevTlBalGt0                         sql.NullInt32
	NumSats                                sql.NullInt32
	NumTl120dpd2m                          sql.NullInt32
	NumTl30dpd                             sql.NullInt32
	NumTl90gDpd24m                         sql.NullInt32
	NumTlOpPast12m                         sql.NullInt32
	PctTlNvrDlq                            sql.NullInt32
	PercentBcGt75                          sql.NullInt32
	PubRecBankruptcies                     sql.NullInt32
	TaxLiens                               sql.NullInt32
	TotHiCredLim                           sql.NullInt32
	TotalBalExMort                         sql.NullInt32
	TotalBcLimit                           sql.NullInt32
	TotalIlHighCreditLimit                 sql.NullInt32
	RevolBalJoint                          sql.NullInt32
	SecAppEarliestCrLine                   sql.NullInt32
	SecAppInqLast6mths                     sql.NullInt32
	SecAppMortAcc                          sql.NullInt32
	SecAppOpenAcc                          sql.NullInt32
	SecAppRevolUtil                        sql.NullInt32
	SecAppOpenActIl                        sql.NullInt32
	SecAppNumRevAccts                      sql.NullInt32
	SecAppChargeoffWithin12Mths            sql.NullInt32
	SecAppCollections12MthsExMed           sql.NullInt32
	SecAppMthsSinceLastMajorDerog          sql.NullInt32
	HardshipFlag                           sql.NullString
	HardshipType                           sql.NullString
	HardshipReason                         sql.NullString
	HardshipStatus                         sql.NullString
	DeferralTerm                           sql.NullString
	HardshipAmount                         sql.NullInt32
	HardshipStartDate                      sql.NullString
	HardshipEndDate                        sql.NullString
	PaymentPlanStartDate                   sql.NullString
	HardshipLength                         sql.NullInt32
	HardshipDpd                            sql.NullString
	HardshipLoanStatus                     sql.NullString
	OrigProjectedAdditionalAccruedInterest sql.NullInt32
	HardshipPayoffBalanceAmount            sql.NullInt32
	HardshipLastPaymentAmount              sql.NullInt32
	DisbursementMethod                     sql.NullString
	DebtSettlementFlag                     sql.NullString
	DebtSettlementFlagDate                 sql.NullString
	SettlementStatus                       sql.NullString
	SettlementDate                         sql.NullString
	SettlementAmount                       sql.NullInt32
	SettlementPercentage                   sql.NullInt32
	SettlementTerm                         sql.NullString
	CountryID                              sql.NullInt32
	Employer                               sql.NullString
	EmploymentType                         sql.NullInt32
	EmpOrderNum                            sql.NullInt32
	GrossMonthlyIncome                     sql.NullInt32
	LenEmpMons                             sql.NullInt32
	LenEmpYears                            sql.NullInt32
	Position                               sql.NullString
	RetiredFlag                            sql.NullString
	SelfEmpFlag                            sql.NullString
	State                                  sql.NullString
	CreatedTime                            time.Time
	UpdatedTime                            time.Time
}
